### ISSUE TITLE
偶发数据重复

### ISSUE THREAD

**Issue by arch3754** [qiniu/logkit#1010]
在1.5.1 版本中从 kafka 拿数据时,偶发会有最后一条数据重复的问题,是在 1.5.4 Lag()函数的部分解决了吗?

func (r *Reader) Lag() (*LagInfo, error) {
	if r.Consumer == nil {
		return nil, errors.New("kafka consumer is closed")
	}
	marks := r.Consumer.HighWaterMarks()
	rl := &LagInfo{
		SizeUnit: "records",
		Size:     0,
	}
	for _, ptv := range marks {
		for _, v := range ptv {
			rl.Size += v
		}
	}
	r.lock.Lock()
	for _, ptv := range r.currentOffsets {
		for _, v := range ptv {
			rl.Size -= v + 1 //HighWaterMarks 拿到的是下一个数据的Offset，所以实际在算size的时候多了1，要在现在扣掉。
		}
	}
	r.lock.Unlock()
	return rl, nil
}

**Comment by zhangdavids** [comment]
:wave:
