### ISSUE TITLE
编译失败->Cannot use `e` (type *Echo) as type *echo.Echo

### ISSUE THREAD

**Issue by hongdanyang1991** [qiniu/logkit#111]
提示出错信息：
./logkit.go:152:26: cannot use e (type *"github.com/labstack/echo".Echo) as type *"github.com/qiniu/logkit/vendor/github.com/labstack/echo".Echo in argument to mgr.NewRestService

**Comment by wonderflow** [comment]
是直接下载后编译的吗？ 

有没有 `govendor sync`

**Comment by hongdanyang1991** [comment]
@wonderflow 不知道为什么gogland，echo依赖有2份，一个在github.com/labstack/...下，另外一个在github.com/qiniu/logkit/vendor/github.com/labstack/...下.删除后者，就不报错了。
