### ISSUE TITLE
保存到es中数据重复了！

### ISSUE THREAD

**Issue by hongdanyang1991** [qiniu/logkit#114]
将java web工程产生的日志按行保存到es中，大部分日志记录是重复的。经过测试，效果如下：
1.同时保存2行日志记录，logkit将最后一条日志记录保存到es中2次。
2.同理，tomcat产生的日志记录，在同时刻产生的n条日志记录，logkit都会将最后一条记录保存n次。

**Comment by wonderflow** [comment]
确认下你本地有没有Govendor sync哈，看你的描述，像是以前我们遇到的es client的一个bug，已经给oliver那个es库提PR修复了。

**Comment by hongdanyang1991** [comment]
@wonderflow 已经使用govendor sync了

**Comment by wonderflow** [comment]
可否提供一些实际的数据，以便我们复现排查

**Comment by hongdanyang1991** [comment]
@wonderflow 
`func (s *BulkService) Add(requests ...BulkableRequest) *BulkService {
	for _, r := range requests {
                //添加下面这行代码，上传到es的数据就不会重复。
		log.Errorf("requests-----------------> %s ", requests)
		s.requests = append(s.requests, r)
	}
	return s
}`

**Comment by wonderflow** [comment]
看上去还是olive 库的问题？ 
我本地无法复现

**Comment by wonderflow** [comment]
@hongdanyang1991  看到你们在fork的库开发，非常欢迎提PR过来哈
