### ISSUE TITLE
no Elasticsearch node available 

### ISSUE THREAD

**Issue by phoenix-ll** [qiniu/logkit#121]
在本地es 5.x已经启动,且可以通过localhost:9200访问,但是使用logkit创建runner,将日志采集到es中时报错,生成的配置文件为:
{
  "name": "logkit.runner.20170919100403",
  "reader": {
    "mode": "dir",
    "log_path": "C:\\iNodeLog",
    "read_from": "oldest",
    "encoding": "UTF-8",
    "ignore_hidden": "true",
    "ignore_file_suffix": ".pid,.swap,.go,.conf,.tar.gz,.tar,.zip,.a,.o,.so"
  },
  "parser": {
    "type": "raw",
    "name": "pandora.parser.20170919100204"
  },
  "senders": [
    {
      "sender_type": "elasticsearch",
      "elastic_host": "localhost:9200",
      "elastic_index": "logkit",
      "elastic_type": "iNode",
      "fault_tolerant": "true",
      "ft_save_log_path": "E:\\logkit_windows\\ft_save",
      "ft_sync_every": "10",
      "ft_strategy": "backup_only",
      "ft_memory_channel": "false"
    }
  ]
}

**Comment by wonderflow** [comment]
报错的内容是  “no Elasticsearch node available” 吗？
可否把完整的logkit报错日志贴一下哈

**Comment by phoenix-ll** [comment]
不是后台报错  是前台的错误提示  :失败 NewRunner(logkit.runner.20170919161103) failed: no Elasticsearch node available  我用的es版本是elasticsearch-5.6.0.msi,  将elastic_host设置为另一个2.4的版本则创建成功 , 请问是es版本的问题吗

**Comment by wonderflow** [comment]
有可能是logkit对5.0的支持有一些问题，我们查一下，多谢反馈。

也非常欢迎提PR哈。

**Comment by phoenix-ll** [comment]
多谢解答

**Comment by yangwenmai** [comment]
I'm working in process this bug in es5.x and es 6.x.

**Comment by wonderflow** [comment]
目前只支持es2.X和es5， #212 支持ES6

**Comment by wonderflow** [comment]
fixed by #212

**Comment by joway** [comment]
我使用 es 5.3.2 , 以及logkit 1.4.0 以及最新 dev 仓库都依旧会报 no Elasticsearch node available 的错误 , 貌似这个问题并没有完全修复 ?

**Comment by yangwenmai** [comment]
我实测用 es v5.3.2 以及最新的 logkit v1.4.1 没有重现 `no Elasticsearch node available` 错误。

你能否提供更详细的环境和配置信息呢？包括你的 es 信息。

**Comment by joway** [comment]
找到了原因，是因为我没有手动指定 es version 的版本，导致它默认认为我是 es3 好像。手动指定     
 "elastic_version": "5.x" 可破。文档上貌似没写这个 ?

**Comment by wonderflow** [comment]
文档已添加 https://github.com/qiniu/logkit/wiki/ElasticSearch-Sender 

@joway
