### ISSUE TITLE
docker 镜像启动 无异常，但是浏览器无法访问

### ISSUE THREAD

**Issue by hongdanyang1991** [qiniu/logkit#137]
docker 启动命令
docker run -d -p 3000:3000 -v /Users/hong/Desktop/confs:/logs/path -v /Users/hong/Desktop/logs:/logs/path wonderflow/logkit

启动后，通过docker logs [CONTAINER ID] 显示如下：
2017/09/30 06:16:34 [INFO][github.com/qiniu/logkit/conf] load_conf.go:71: Use the config file of  logkit.conf
2017/09/30 06:16:34 [INFO][github.com/qiniu/logkit] logkit.go:114: Welcome to use Logkit, Version: v1.2.3

Config: main.Config{MaxProcs:8, DebugLevel:1, ProfileHost:"", ConfsPath:[]string{"confs*"}, CleanSelfLog:true, CleanSelfDir:"", CleanSelfPattern:"", TimeLayouts:[]string(nil), CleanSelfLogCnt:0, StaticRootPath:"./public", ManagerConfig:mgr.ManagerConfig{BindHost:"localhost:3000", Idc:"", Zone:"", RestDir:""}}
2017/09/30 06:16:34 [WARN][github.com/qiniu/logkit/mgr] mgr.go:375: start to add watcher of conf path /app/confs
2017/09/30 06:16:34 [INFO][github.com/qiniu/logkit/mgr] mgr.go:425: successfully restored 0 runners in /app/.logkitconfs web rest dir
2017/09/30 06:16:34 [INFO][github.com/qiniu/logkit/mgr] rest.go:87: successfully start RestService and bind address on localhost:3000

但是浏览器无法访问 localhost:3000

**Comment by wonderflow** [comment]
是docker的版本更新了我们没有及时更新dockerhub镜像，你可以尝试本地build一个哈。
也可以pull我刚刚上传的

```
docker pull wonderflow/logkit:v1.3.2
```

**Comment by hongdanyang1991** [comment]
wonderflow/logkit:v1.3.2的镜像也是无法通过浏览器访问 localhost:3000

**Comment by wonderflow** [comment]
这个跟docker的启动方式有关，不同操作系统不一样。如果是windows、mac需要找到对应的虚拟机IP，linux也需要在host模式下运行docker才可以这样访问

**Comment by wonderflow** [comment]
可以试下这个版本：

`docker pull wonderflow/logkit:v1.3.4`

访问 http://127.0.0.1:3000
