### ISSUE TITLE
如何本地调试源码？

### ISSUE THREAD

**Issue by momsbaby** [qiniu/logkit#159]
请教大牛，如何调试logkit源码

**Comment by wonderflow** [comment]
调试的话，`go run logkit.go -f logkit.conf` 即可，代码里面加上你的打印信息。

可以参考下 https://github.com/qiniu/logkit/wiki/%E6%9C%AC%E5%9C%B0%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97 搭建起本地go环境
