### ISSUE TITLE
elasticsearch sender 字段重命名导致其它字段丢失

### ISSUE THREAD

**Issue by phoenix-ll** [qiniu/logkit#193]
## Bug report
elasticsearch sender 字段重命名导致其它字段丢失

#### logkit 版本：
v1.3.5 

### 复现过程操作步骤:
1.选择elasticsearch sender发送数据
2假设此时每条数据中有两个字段:raw , timestamp
3.使用elastic_keys 对字段重命名 如: "elastic_keys":"timestamp @timestamp"

### 预期表现:
发送至es中数据应该包含 raw, @timestamp两个字段

### 实际情况:
只有@timestamp 一个字段

**Comment by lvheyang** [comment]
这里按照pandora sender 的模式来看，"elastic_keys":"timestamp @timestamp, ..." 应该代表这个字段改名字，同时带上其他字段

**Comment by lvheyang** [comment]
我理解这个 elastic_keys 的含义是，选择所有发送到es的字段，并且可以重命名，如果只改部分字段，其他字段都发到es，那么就可以加上 省略号
