### ISSUE TITLE
增强replace transformer 使其支持正则替换

### ISSUE THREAD

**Issue by phoenix-ll** [qiniu/logkit#194]
### 功能描述:
增强replace transformer 使其支持正则替换

### 背景及目标:
现阶段replace transformer 只支持字符串匹配替换,但是很多情况下需要用到正则去匹配替换,包括通过正则捕获,对字段值进行重组.

**Comment by wonderflow** [comment]
@phoenix-ll  欢迎PR哈，确实有必要做

**Comment by phoenix-ll** [comment]
ok
