### ISSUE TITLE
vendor 入库

### ISSUE THREAD

**Issue by flyer103** [qiniu/logkit#207]
### 功能描述:
将 vendor 的 pkg 入库，使得项目开箱即用，方便开发者贡献。

### 背景及目标:
获取 vendor pkg、熟悉 vendor 工具等与开发项目的关系不大，同时操作也比较耗时，开发者也没有必要熟悉项目所使用的管理 vendor 的工具。故可考虑将 vendor 入库，使得开发者的注意力更集中在项目功能或 bugfix 上。

**Comment by wonderflow** [comment]
好建议，感谢
