### ISSUE TITLE
logkit的系统信息采集，没有携带机器标识，这个是正常么？

### ISSUE THREAD

**Issue by momsbaby** [qiniu/logkit#238]
不携带机器标识（如ip或者机器名称），采集上来怎么区分？

**Comment by andrewei1316** [comment]
您好， logkit 从  v1.3.6 开始已经支持在发送的时候自动添加机器标识了，不过暂时仅支持 Pandora sender，将 “pandora_extra_info” 配置为 “true” 就可以开启该功能，详细信息您可以参考 https://github.com/qiniu/logkit/wiki/Pandora-Sender 。

**Comment by momsbaby** [comment]
@andrewei1316 为什么不在metric本身就加上机器标识呢，反而在sender里做，这个应该是都需要的，否则无法区分

**Comment by wonderflow** [comment]
你说的有道理的，我们会考虑，也欢迎PR哈
