### ISSUE TITLE
script transformer

### ISSUE THREAD

**Issue by phoenix-ll** [qiniu/logkit#260]
### 功能描述:
增加一个script transformer,用户通过填写简单的js脚本,达到灵活transform字段的目的

### 背景及目标:
robertkrimen/otto可以实现在go中执行js代码字符串

有些日志 用 i,e,d 等表示日志level,希望通过一个transformer来将字段值转换为 info, error, debug
 {
      "newKey": "level",
      "oldKey": "level",
      "script": "
           switch(level){
           case "i":
               level="info";
           case "e":
               level="error";
           case "d":
               level="debug";
          }
      ",
      "type": "script"
    },

**Comment by wonderflow** [comment]
可以，欢迎PR
