### ISSUE TITLE
json相关的用更快的库替换

### ISSUE THREAD

**Issue by wonderflow** [qiniu/logkit#277]
https://github.com/json-iterator/go 号称数倍于 enconding/json 

benchmark先行。

**Comment by qinhao** [comment]
最近我用 [https://github.com/json-iterator/go](https://github.com/json-iterator/go) 替换了 `JSON Parse` 中的 `encoding/josn` 部分，并使用 [ Flame Graphs](http://www.brendangregg.com/flamegraphs.html) 工具简单地进行了对比，发现替换后 CPU 在 `Parse` 这块占用比替换前少了一半的时间左右。具体可参看：

[logkit_perf_flame_graphs.zip](https://github.com/qiniu/logkit/files/1597046/logkit_perf_flame_graphs.zip)

其中，`perf1.svg` 是替换后的火焰图，CPU 在 `Parse` 部本消耗的比重大约在 10.29%；`perf2.svg` 是替换前的火焰图，CPU 在 `Parse` 部分占用的比例大约在  22.04%。所以，我觉得 JSON 解析库的替换很有必要。如果可以的话，回头我把相关代码整理一下，然后提 RP 过来 ；-）

**Comment by wonderflow** [comment]
欢迎PR
