### ISSUE TITLE
从文件读取dir模式下，想获取日志具体来源路径datasource， 出现了一些问题

### ISSUE THREAD

**Issue by zqzgit** [qiniu/logkit#284]
从文件读取dir模式下，想获取日志具体来源路径datasource，改造seqfile.go文件在Source()接口中调用sf.currFile得到当前处理文件，但是每条日志入到es中datasource字段都是最后日志文件的路径；调试了好久没找到问题的所在

**Comment by wonderflow** [comment]
fixed by https://github.com/qiniu/logkit/pull/290  

因为读取的时候是读到bufferreader的缓冲区，所以当buffer reader还在读前一部分数据的时候，可能底层的多文件拼接的seq reader已经读取到下一个文件，而此时调用的结果会是下一个文件的结果，所以出现异常。目前这个PR没有解决这个问题，但是也可以使用。大多数case是不会影响的
