### ISSUE TITLE
数据同步到 TsDB 中序列名称错误

### ISSUE THREAD

**Issue by daxiong123** [qiniu/logkit#371]
### logkit 相关配置:

![image](https://user-images.githubusercontent.com/2648157/37337335-e173054c-26ee-11e8-9adf-509332f6203a.png)

### 预期表现:

数据同步到 TsDB 中，仓库名称为 ``cloud_buy`` 序列名称为 ``pet_order``

### 实际情况:

数据同步到 TsDB 中，仓库名称为 ``cloud_buy`` 序列名称为 ``cloud_buy``

![image](https://user-images.githubusercontent.com/2648157/37337496-6d4f13ee-26ef-11e8-8630-f8140067cb12.png)

**Comment by wonderflow** [comment]
已修复，多谢反馈
