### ISSUE TITLE
当Reader文件失败时，阻塞前端提交

### ISSUE THREAD

**Issue by xxh2000** [qiniu/logkit#457]
### 复现过程操作步骤:

1. 新建一个Runner,从dir读取文件，但是这个dir不存在
2. 后端会sleep几秒后不断重试
3. 这时候在前端新建一个新的runner,在最后一步提交的时候，点击确认并提交没有响应
### 预期表现:

提交成功

### 实际情况:

点击确认提交没有响应，无法提交一个新的runner

### 相关日志等其他信息:

![image](https://user-images.githubusercontent.com/10917455/39566237-83a7eba4-4eed-11e8-9ae9-0a681796b710.png)

![image](https://user-images.githubusercontent.com/10917455/39566300-b813192c-4eed-11e8-9b6e-1521def88e59.png)

![image](https://user-images.githubusercontent.com/10917455/39566331-ce1e88be-4eed-11e8-9622-3fe01415bbb9.png)

**Comment by wonderflow** [comment]
这个情况我们目前没有复现，可以用最新的logkit代码试一下吗

**Comment by wonderflow** [comment]
最新的代码已经修复了这个问题，但是还没有发布v1.4.8,可以等1.4.8使用
