### ISSUE TITLE
是否增加登录权限功能

### ISSUE THREAD

**Issue by xxh2000** [qiniu/logkit#473]
目前logkit前端没有登录认证， 在使用过程中难免要跨部门跨用户协作使用，请问是否在将来有增加登录模块和权限模块的设计。

**Comment by wonderflow** [comment]
这块我们在高级版做了，社区版暂时不考虑加入，欢迎体验[logkit-pro](http://logkit-pro.qiniu.com)

**Comment by xxh2000** [comment]
好的

**Comment by xxh2000** [comment]
@wonderflow logkit-pro 和社区版相比，有什么特性呢，或者功能什么的，能否简单说一下，谢谢

**Comment by wonderflow** [comment]
1. 增加了更多的管理类操作，如统一配置，批量分发。
2. 在配置方面，增加了更多前端优化，使得配置更人性化，自动化。
3. 增加了更多的监控，如runner运行监控、机器监控等
