### ISSUE TITLE
sender 发送时候能够携带本地机器信息

### ISSUE THREAD

**Issue by joway** [qiniu/logkit#489]
### 功能描述:

目前只有 pandora_sender 具备携带本地信息的功能。https://github.com/qiniu/logkit/pull/214 。希望这个发送本地信息能够被整合到所有sender上(如果可以的话)。

### 用户场景: [这个功能重要度、优先级等等]

对于分析日志产生的机器情况非常重要。

**Comment by wonderflow** [comment]
在runner全局配置加上 "extra_info":true 即可

https://github.com/qiniu/logkit/wiki/Runner%E4%B9%8B%E6%95%B0%E6%8D%AE%E9%87%87%E9%9B%86%E9%85%8D%E7%BD%AE
