### ISSUE TITLE
采集日志,文件重命名导致重复读取数据

### ISSUE THREAD

**Issue by phoenix-ll** [qiniu/logkit#498]
## Bug report
采集日志,文件重命名导致重复读取数据
### 运行环境:
linux
#### logkit 版本：
1.4.9
### 复现过程操作步骤:
1.创建三个runner,分别以tailx模式、dir模式、file模式采集 /log/test.log
①tailx模式, log_path:"/log/*"
②dir模式,  log_path:"/log"
③file模式, log_path:"/log/test.log"
采集正常
2.日志采集完成后,将test.log重命名为test2.log
①tailx模式,重复采集整个test2.log日志
②dir模式,未重复采集
③file模式,未重复采集
3.向test2.log中追加数据
①tailx模式再次重复采集整个test2.log
②dir模式重复采集整个test2.log
③file模式,未重复采集
4.将test2.log再次命名为test.log
①tailx模式,重复采集
②dir模式,未重复采集
③file模式,重复采集整个test.log

### 功能描述:
希望解决重命名导致重复采集的问题,在meta记录读取文件位置也采用inode作为标记
### 修改后文档内容

**Comment by wonderflow** [comment]
这个现象在我看来是合理的。

另外，记录inode并不能解决问题，因为系统里的inode是会被复用的，不是唯一值，如果我记录了inode，反而会导致新文件不读的bug。
