### ISSUE TITLE
windows环境下  tailx模式报错

### ISSUE THREAD

**Issue by phoenix-ll** [qiniu/logkit#500]
### 复现过程操作步骤:
在windows环境下使用tailx模式采集日志, fail to newMeta  导致无法采集日志

**Comment by wonderflow** [comment]
可以写一下 fail to newMeta 的完整错误日志吗

**Comment by phoenix-ll** [comment]
错误日志:
2018/05/24 17:24:42 [ERROR][github.com/qiniu/logkit/reader] meta.go:75: fail to newMeta cannot create meta\runner.20180523165621_789356349\C:_logs2_test.log, err:mkdir meta\runner.20180523165621_789356349\C:_logs2_test.log: The directory name is invalid.
2018/05/24 17:24:42 [ERROR][github.com/qiniu/logkit/reader] meta.go:92: check dir meta\runner.20180523165621_789356349\C:_logs2_test.log error mkdir meta\runner.20180523165621_789356349\C:_logs2_test.log: The directory name is invalid.
2018/05/24 17:24:42 [ERROR][github.com/qiniu/logkit/reader] mutireader.go:374: Runner[runner.20180523165621] NewActiveReader for matches C:\logs2\test.log error mkdir meta\runner.20180523165621_789356349\C:_logs2_test.log: The directory name is invalid., ignore this match...

**Comment by phoenix-ll** [comment]
reader配置:
    "reader": {
        "mode": "tailx",
        "runner_name": "runner.20180523165621",
        "encoding": "UTF-8",
        "datasource_tag": "datasource",
        "expire": "100h",
        "stat_interval": "3m",
        "name": "runner.20180523165621",
        "log_path": "C:\\logs2\\*",
        "read_from": "oldest"
    }

**Comment by wonderflow** [comment]
可以先手动写一下 "meta":"meta" 解决一下，看上去是windows不支持自动生成的meta文件名

**Comment by phoenix-ll** [comment]
应该是win环境下自动生成的meta\runner.20180523165621_789356349\C:_logs2_test.log目录名有问题

**Comment by Unknwon** [comment]
`meta\runner.20180523165621_789356349\C:_logs2_test.log` 路径重新出现了盘符（C:），猜测是 `*path.Join` 时出现的问题
