### ISSUE TITLE
读取了每行的换行符

### ISSUE THREAD

**Issue by xxh2000** [qiniu/logkit#510]
在读取每行是会把换行符读取，在自己拿到采集后的数据进行处理有时候因为换行符有点不方便，是否有这个必要读取换行符？

![image](https://user-images.githubusercontent.com/10917455/40640590-3e4dabbe-6349-11e8-8817-0f88fd2cb31a.png)

**Comment by wonderflow** [comment]
换行符是文件的内容一部分，尤其是在日志是多行的情况下，没有换行符可能无法阅读。
这个有必要保留的
