### ISSUE TITLE
前端显示问题

### ISSUE THREAD

**Issue by xxh2000** [qiniu/logkit#614]
如下图
![image](https://user-images.githubusercontent.com/10917455/42875226-ccfbb89a-8ab5-11e8-985d-c853cbb15a87.png)

在鼠标移动到删除图标上的时候，显示的提示是删除收集器，是否应该显示删除机器呢？还是设计本如此

**Comment by wonderflow** [comment]
logkit的集群功能不再维护

**Comment by xxh2000** [comment]
只有Pro 版维护么？
