### ISSUE TITLE
Release windows版本没有logkit.exe

### ISSUE THREAD

**Issue by xxh2000** [qiniu/logkit#615]
下载release windows版本解压后没有logkit.exe,是logkit, 无法在windows上运行

版本：1.5.1，其他版本也如此。

![image](https://user-images.githubusercontent.com/10917455/42876181-78f4b44c-8ab8-11e8-8a14-5c4b14a3bbf4.png)

**Comment by Unknwon** [comment]
哈哈哈哈，logkit 加个 .exe 后缀就行了

**Comment by wonderflow** [comment]
恩，加个`.exe` 后缀哈

**Comment by wonderflow** [comment]
在Download那边下载的是修复的

**Comment by xxh2000** [comment]
哈哈，神操作  :+1: )
