### ISSUE TITLE
源码编译的时候报错

### ISSUE THREAD

**Issue by daozhu** [qiniu/logkit#690]
## Bug Report
源码编译的时候报错了

```
 go build -o logkit logkit.go
# command-line-arguments
./logkit.go:287:26: cannot use e (type *"github.com/labstack/echo".Echo) as type *"github.com/qiniu/logkit/vendor/github.com/labstack/echo".Echo in argument to mgr.NewRestService
```

### 运行环境:
rancherOS  pi 版本   (  aarch64 )
#### logkit 版本：
afa2f6acfd2b8dfbb3a586ff306be2d849e79f3d

最新的源码编译的

#### 操作系统版本：
```
uname -a

Linux rancher 4.9.80-hypriotos-v8 #1 SMP PREEMPT Thu Apr 26 17:51:07 UTC 2018 aarch64 GNU/Linux
```

### 复现过程操作步骤：

1.  go build -o logkit logkit.go

**Comment by wonderflow** [comment]
应该是你gopath里有 echo的库，然后logkit vendor里也有，你把gopath调整下就好了

**Comment by daozhu** [comment]
ok 了, 我在GOPATH 目录下编译就没事了,感谢

**Comment by LittleBryant** [comment]
我报的也是这个错误，我没有进行编译，运行的时候提示这个错误，大佬，怎么解决？

**Comment by EsmeraldaYS** [comment]
咋关闭了呢？
