### ISSUE TITLE
Oracle 数据源支持

### ISSUE THREAD

**Issue by xxh2000** [qiniu/logkit#750]
请问是否有支持Oracle的计划，我自己实现了读取oralce数据的功能，使用[goracle](https://github.com/go-goracle/goracle), 该lib使用[odpi](https://github.com/oracle/odpi)来实现对oralce的操作，使用odpi需要安装oracle的so链接库，貌似目前没有纯go的oralce库，都得依赖oracle的so链接库，如果集成进来，会在部署的时候需要额外预装oracle-client。这种方式logkit觉得可以接受的我可以提交一个patch。不便的话就不加了。

**Comment by chen-wenhao** [comment]
欢迎提交，一起交流

**Comment by wonderflow** [comment]
欢迎提交
