### ISSUE TITLE
多行日志收集时，使用"grok_mode": "multi"，grok会把日志中的换行符替换为空格解析

### ISSUE THREAD

**Issue by ccjetweat** [qiniu/logkit#851]
官方文档说使用"grok_mode": "multi"，grok解析时会把换行符替换成空格，数据展示换行问题怎么解决呀

**Comment by wonderflow** [comment]
不用grok_mode multi，在reader中使用 head_pattern解决多行问题

**Comment by ccjetweat** [comment]
不用grok_mode: multi的话，解析的时候就不能解析每个字段了，解析失败的数据全部会放到pandora_stash字段了

**Comment by ccjetweat** [comment]
> 不用grok_mode multi，在reader中使用 head_pattern解决多行问题

不用grok_mode: multi的话，解析的时候就不能解析每个字段了，解析失败的数据全部会放到pandora_stash字段了

**Comment by wonderflow** [comment]
在head_pattern处理掉多行，解析的时候依然可以解析每个字段，你在写grok的时候要考虑换行
