### ISSUE TITLE
mysql reader 各个字段均被base64encode

### ISSUE THREAD

**Issue by lxm** [qiniu/logkit#87]
mysql reader 各个字段均被base64encode
这个可以配置么，收集上来的日志每个字段都是base64encode过的

**Comment by wonderflow** [comment]
意思是mysql reader自动帮你base64encode了吗？ 是否可以描述下 具体是什么情况。 mysql里面是什么字段，收集后是什么字段

**Comment by lxm** [comment]
收集上来的数据如图
![image](https://user-images.githubusercontent.com/1918195/29757362-f184a83e-8bdd-11e7-9ee7-0d6b342bfb63.png)
我的reader配置
  "reader": {
    "mode": "mysql",
    "mysql_datasource": "",
    "mysql_database": "",
    "mysql_sql": "select id,job_id,scene_id,lesson_id,process,type,msg,created_at,updated_at,done_at,expire,status,imagename from virt_job_result where date(created_at) >= date(CURRENT_TIMESTAMP)",
    "mysql_limit_batch": "100",
    "mysql_cron": "@every 1m",
    "mysql_exec_onstart": "true"
  }

**Comment by wonderflow** [comment]
fixed by  https://github.com/qiniu/logkit/pull/89

**Comment by daxiong123** [comment]
![image](https://user-images.githubusercontent.com/2648157/37331014-b51a45fc-26dd-11e8-9f3d-fcf4d15ab56a.png)

Mysql 数据依然被 base64encode
